#+TITLE: My Emacs Config

* IMPORTANT
 NOTE: The first time you load your configuration on a new machine, you'll
 need to run the following command interactively so that mode line icons
 display correctly:
 =M-x all-the-icons-install-fonts=

 All =init-*.el= configuration files are under the =lisp= directory
* Packages
** straight.el
This configuration uses the [[https://github.com/radian-software/straight.el][straight.el]] package manager
** vterm
need to install =cmake=
*** Homebrew 
#+begin_src
brew install cmake
#+end_src

*** Nixos
add this to your =home.nix= to install emacs with vterm built in.
#+begin_src nix
programs.emacs = {
	enable = true;
	extraPackages = epkgs: [
	epkgs.vterm
	];
};
#+end_src
*** Arch
#+begin_src
sudo pacman -S cmake
#+end_src

*** Void Linux
#+begin_src 
sudo xbps-install -S cmake libtool
#+end_src

** Ditaa
used to make graphics out of ASCII in org src-blocks. Find where ever =ditaa.jar= is and
link it to a folder in =.emacs.d=. the default folder in =init-org.el= is =links=

** LSP-Mode
A few major-modes for lanugages have been enabled for code completion in =init-code.el= 
#+begin_src elisp
  (setq lsp-keymap-prefix "C-c l")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)

	 ;; c lsp lang
     (c-mode . lsp)
     (c++-mode . lsp)
	 (zig-mode . lsp)
	 (mhtml-mode .lsp)
	 (swift-mode . lsp)
	 (go-mode . lsp)
	 (csharp-mode . lsp)
     ;; if you want which-key integration
     (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)
#+end_src>
For these to work, just installing the language server of each language should do it.
If you want a new language, install the major mode and append the list of languages
#+begin_src elisp
;; install major mode
(use-package lang-mode
  :straight t)

;; Append to list
(lang-mode . lsp)
#+end_src>



* Key bindings
The default leader key is <SPC>. The global is <C-SPC>, use this whenever
evil mode is not used. Currently magit and dired need to use the global
prefix.
